viperproject/viperserver

- .gitignore
- src/main/scala/viper/server/VerificationWorker.scala
>  **Pull request** :twisted_rightwards_arrows: created by **@aterga** on 2019-05-26 13:21
> Last updated on 2020-02-03 15:46
> Original Bitbucket pull request id: 10
>
> Participants:
>
> * **@mschwerhoff** (reviewer)
>
> Source: https://github.com/viperproject/viperserver/commit/bd4559f52f7a1a46707003fcbaabecc662a90a46 on branch `arshavir/viperserver-plugin-aware-reporting/default`
> Destination: https://github.com/viperproject/viperserver/commit/7cc7ce5224a723ab1fcdbe2e7ea0cbfbd727fcab on branch `master`
>
> State: **`OPEN`**
For details, see [Silver PL 120](https://github.com/viperproject/silver/pull/421).
> mapVerificationResult is now applied automatically in Silver

- src/main/scala/viper/server/core/ViperCache.scala
- src/test/scala/viper/server/core/AsyncCoreServerSpec.scala
Reenables unit tests for concurrent verification jobs and fixes ViperServer to clear the cache whenever it starts.
This PR requires the changes from [Silver PR #503](https://github.com/viperproject/silver/pull/503) and [Silicon PR #533](https://github.com/viperproject/silicon/pull/533)
> Unit Tests with Concurrent Verifications

- src/main/scala/viper/server/ViperServerRunner.scala
- src/main/scala/viper/server/vsi/HTTP.scala
- src/main/scala/viper/server/vsi/Terminator.scala
- src/test/scala/viper/server/core/ViperServerHttpSpec.scala
The HTTP server now offers a way to await its shutdown. The Terminator actor no longer uses some actor system and execution context but takes `VerificationExecutionContext`. However, the execution context is not terminated but is an obligation of clients to terminate when appropriate.
> Fixes Termination of HTTP Server

- .github/workflows/scala.yml
@fpoli will periodically create PRs when the Viper Tools change. To reduce the number of unnecessary PRs that are created even though the tools contained in the ZIP files have not changed, this PR compares the commit hashes of ViperServer, Silver, Silicon, and Carbon with those used for (already existing) nightly releases. A new nightly release will only be triggered in the `viper-ide` repository if at least one commit hash has changed.
The check, as implemented in this PR, works because `versions.txt` stores the current commit hashes and is used as body of the nightly release. Thus, one can easily check the content of the current `versions.txt` file against the bodies of the releases.
> Create Nightly Release Only on Change

- src/main/scala/viper/server/frontends/http/jsonWriters/ViperIDEProtocol.scala
- src/main/scala/viper/server/frontends/lsp/DataProtocol.scala
- src/main/scala/viper/server/utility/ProgramDefinitionsProvider.scala
The goal o this PR is to pass **typed** information about program definitions to the IDE. To do this, we implement (more-or-less) proper serialization of Viper types (currently, into JSON), which might be useful by itself. 
This PR should be merged after [Silver PR 523](https://github.com/viperproject/silver/pull/523)
> Support typed definitions in ProgramDefinitionsProvider

- src/main/scala/viper/server/core/ViperCoreServer.scala
- src/main/scala/viper/server/frontends/http/ViperHttpServer.scala
- src/main/scala/viper/server/frontends/lsp/ViperServerService.scala
- src/main/scala/viper/server/vsi/HTTP.scala
- src/main/scala/viper/server/vsi/VerificationServer.scala
- src/test/scala/viper/server/core/CoreServerSpec.scala
- src/test/scala/viper/server/core/ViperServerHttpSpec.scala
I suspect that one of the reason for the failing viper-ide tests is that the IDE performs a POST request before the server is actually up and running.
This PR changes the `start` function to return a future. This future is completed when the server is ready. Only then the server's port number will be output on standard output to indicate to clients that it is ready.
> Wait for Server Start

- .github/workflows/scala.yml
- src/main/scala/viper/server/core/ViperCoreServer.scala
- src/main/scala/viper/server/frontends/http/ViperHttpServer.scala
Fixes caching by using the filename as program ID instead of generating a new one for each parse operation. This effectively disables caching as the cache's lookup depends on the program ID.
Additionally, the CI is adapted to use the current release candidate when running the CI in `release` configuration.
Note that this PR reenables caching for Viper-IDE but the error messages do not (yet) indicate that a verification error comes from the cache. [Silver PR #533](https://github.com/viperproject/silver/pull/533) fixes the error message
> Fixes Caching

- build.sbt
- src/main/scala/viper/server/ViperConfig.scala
- src/main/scala/viper/server/core/VerificationWorker.scala
- src/main/scala/viper/server/core/ViperCache.scala
- src/main/scala/viper/server/core/ViperCoreServer.scala
- src/main/scala/viper/server/frontends/http/ViperHttpServer.scala
- src/main/scala/viper/server/vsi/Cache.scala
- Added serialization & deserialization functionality to the ViperCache object
- Added config option to specify a cache file
> Write Cache to file

- .github/workflows/scala.yml
- docker/Dockerfile
- src/main/scala/viper/server/core/ViperCache.scala
- src/main/scala/viper/server/core/ViperCoreServerUtils.scala
- src/test/resources/viper/changed-axiom/version1.vpr
- src/test/resources/viper/changed-axiom/version2.vpr
- src/test/resources/viper/changed-function/version1.vpr
- src/test/resources/viper/changed-function/version2.vpr
- src/test/resources/viper/identical-versions/version1.vpr
- src/test/resources/viper/identical-versions/version2.vpr
- src/test/scala/viper/server/core/CoreServerSpec.scala
This PR correctly sets the `cached` flag for cached errors to `true`. Furthermore, several unit tests have been added including a check that cache results are not mixed up between backends (in an attempt to understand [Silicon Issue #550](https://github.com/viperproject/silver/issues/550) which is however not solved yet.
Additionally, Boogie has been added to the CI such that tests involving Carbon can be executed
> Fixes Cached Flag for Errors

- src/main/resources/application.conf
- src/main/scala/viper/server/vsi/VerificationServer.scala
stops ViperServer from crashing if parsing takes longer than 5s and emits a warning instead if streaming parsing messages does not start within that time frame
> Support for Viper files with long parsing times

- src/main/scala/viper/server/core/AstWorker.scala
- src/main/scala/viper/server/core/MessageReportingTask.scala
- src/main/scala/viper/server/core/VerificationWorker.scala
- src/main/scala/viper/server/frontends/lsp/FileManager.scala
- src/test/resources/viper/refute-simple.vpr
- src/test/resources/viper/refute.vpr
- src/test/resources/viper/refute1.vpr
- src/test/resources/viper/refute2.vpr
- src/test/resources/viper/reordered-refutes/version1.vpr
- src/test/resources/viper/reordered-refutes/version2.vpr
- src/test/scala/viper/server/core/CoreServerSpec.scala
Requires [Silver #641](https://github.com/viperproject/silver/pull/641)
> Support for Plugins

- src/main/scala/viper/server/core/ViperCoreServer.scala
- src/main/scala/viper/server/frontends/http/ViperHttpServer.scala
- src/main/scala/viper/server/frontends/lsp/ViperServerService.scala
- src/main/scala/viper/server/vsi/HTTP.scala
- src/main/scala/viper/server/vsi/VerificationServer.scala
- src/test/scala/viper/server/core/CoreServerSpec.scala
- src/test/scala/viper/server/core/ViperServerHttpSpec.scala
`ViperHttpServer` did not call `start()` on `ViperCoreServer` and instead directly called `start(active_jobs)` on `VerificationServer`. This resulted in an uninitialized cache and thus in an exception whenever ViperServer tries to store a verification result in the cache after a verification.
This PR fixes #111 by making `ViperHttpServer` call `ViperCoreServer.start()` and slightly changing the inheritance such that `VerificationServerHttp` can still configure the server startup (i.e. to bind the HTTP server).
> Fixes Cache Initialization for HTTP Server

- src/main/scala/viper/server/frontends/lsp/ClientCoordinator.scala
- src/main/scala/viper/server/frontends/lsp/FileManager.scala
- src/main/scala/viper/server/frontends/lsp/ViperServerService.scala
- src/main/scala/viper/server/vsi/HTTP.scala
As observed in [Viper-IDE #370](https://github.com/viperproject/viper-ide/issues/370), a subsequent verification might be affected by an earlier abort.
We have observed that ViperServer keeps sending messages to Viper-IDE even though the abort has finished. The probable reason is that the propagation of messages is delayed. Thus, this PR performs these two contributions:
- skip all messages after performing an abort such that a client does not confuse them belonging to a potential subsequent verification job
- abort not just the verification job but also the AST building job
> Improve Verification Aborts

- src/main/scala/viper/server/core/AstWorker.scala
- src/main/scala/viper/server/core/VerificationWorker.scala
- src/main/scala/viper/server/utility/AstGenerator.scala
… and forwarding whitelisted options to ASTProvider.
This is an attempt to fix #165 and #184.
> Making sure plugins get a proper config object

- src/main/scala/viper/server/utility/AstGenerator.scala
Turns out the previous code did not account for parameters being passed ``--like=this`` instead of ``--like that``, and also used the slice function incorrectly.
> Fixing parameter filtering

- src/main/scala/viper/server/frontends/lsp/FileManager.scala
This addresses https://github.com/viperproject/viper-ide/issues/412 and matches the behavior of other tools (e.g. compilers): If there are warnings but no errors, we report the warnings, but the overall verification is marked as a success.
As a result, a program that generates no errors but two warnings leads to a result (displayed in VSCode at the bottom left) that is marked as yellow but starts with a checkmark and states "Successfully verified test.vpr in 0.6 seconds with 2 warnings.". Previously, in this situation, VSCode would report a yellow message marked with a cross stating "Verifying test.vpr failed after 0.8 seconds with 0 errors and 2 warnings."
A result of e.g. one error and two warnings still leads to a red result with a cross saying "Verifying test.vpr failed after 0.6 …
> Report verification as successful when there are warnings but not errors

- src/main/scala/viper/server/frontends/lsp/FileManager.scala
Using a custom backend in LSP interaction seems to fail because only `silicon` or `carbon` are acceptable as backends in `getVerificationCommand` . This PR lifts this restriction.
> Allow custom backends in `getVerificationCommand`

- src/main/scala/viper/server/core/VerificationWorker.scala
This PR should only be accepted after this [Silicon PR](https://github.com/viperproject/silicon/pull/799) and [Carbon PR](https://github.com/viperproject/carbon/pull/491) have been merged and the submodules updated.
Added code to `ViperBackend` to submit programs to the [viper-data-collection backend](https://github.com/viperproject/viper-data-collection) if `—submitForEvaluation` is passed as an argument to the SilFrontend.
> viper-data-collection changes

- .github/workflows/scala.yml
Since Viper-IDE (cf. [Viper-IDE PR #434](https://github.com/viperproject/viper-ide/pull/434))is built with respect to a fixed ViperServer release, we should not delete old nightly releases.
Additionally, this PR removes triggering of Viper-IDE's CI. Instead, we will create a periodic CI job to compare and fetch the latest ViperServer release.
> Adapts to CI to keep nightly releases

- src/main/scala/viper/server/vsi/HTTP.scala
- src/main/scala/viper/server/vsi/Terminator.scala
- src/main/scala/viper/server/vsi/VerificationServer.scala
I've observed errors created by Akka complaining about non-unique names for instances of the Terminator actor when using ViperServer in Gobra's unit tests. A Terminator actor instance is only used during the lifetime of a ViperServer instance but we use a separate ViperServer instance for each unit test that needs such an instance and Akka is apparently not happy that we reuse the same name.
This PR addresses this issue by using a unique name for each Terminator instance.
> Unique name for the Terminator actor

- src/main/scala/viper/server/core/AstWorker.scala
- src/main/scala/viper/server/core/MessageReportingTask.scala
- src/main/scala/viper/server/core/VerificationWorker.scala
Adapting to Silver PR https://github.com/viperproject/silver/pull/854 and making the ``ActorReporter`` plugin aware. Also removing the existing code in ViperServer that transforms entity result messages, since this is now done by the reporter.
> Adapting ActorReporter to Silver changes

- build.sbt
- project/plugins.sbt
The CI encountered today strange errors when trying to initialize `sbt` ([example](https://github.com/viperproject/viperserver/actions/runs/14302944041/job/40082415933)). It seems that all 3 sbt plugins (`com.eed3si9n:sbt-assembly`, `com.typesafe.sbt:sbt-native-package`, and `com.eed3si9n:sbt-buildinfo`) result in `409` errors when trying to download them. While  a `409` error hints at some server-internal conflict related to such a dependency, it remains unclear why this got triggered today.
This PR updates these dependencies.
> Update SBT Dependencies
